package input.comprehensible.data.stories.sources.stories.remote

import input.comprehensible.data.stories.sources.stories.model.StoryData
import input.comprehensible.data.stories.sources.stories.model.StoryElementData

/**
 * A data source for stories that are fetched from a remote server.
 */
class DefaultStoriesRemoteDataSource : StoriesRemoteDataSource {
    override suspend fun generateAiStory(
        learningLanguage: String,
        translationLanguage: String
    ) = AiStoryData(
        content = StoryData(
            id = "ai_story",
            title = "AI Story",
            content = listOf(
                StoryElementData.ParagraphData(
                    sentences = listOf(
                        "Dies ist eine Geschichte, die von KI generiert wurde.",
                        "Es ist nicht real, aber es ist trotzdem interessant.",
                    )
                ),
            )
        ),
        translations = StoryData(
            id = "ai_story",
            title = "AI Story",
            content = listOf(
                StoryElementData.ParagraphData(
                    sentences = listOf(
                        "This is a story generated by AI.",
                        "It is not real, but it is still interesting.",
                    )
                ),
            )
        )
    )
}