package input.comprehensible.features.aistory

import android.os.Build
import com.github.takahirom.roborazzi.ExperimentalRoborazziApi
import com.github.takahirom.roborazzi.RoborazziOptions
import com.github.takahirom.roborazzi.RoborazziRule
import dagger.hilt.android.testing.HiltAndroidTest
import dagger.hilt.android.testing.HiltTestApplication
import input.comprehensible.ComprehensibleInputTestRule
import input.comprehensible.data.sample.SampleStoriesData
import input.comprehensible.features.story.onStoryReader
import input.comprehensible.features.storylist.onStoryList
import input.comprehensible.runTest
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode

@RunWith(RobolectricTestRunner::class)
@HiltAndroidTest
@Config(
    manifest = Config.NONE,
    sdk = [Build.VERSION_CODES.UPSIDE_DOWN_CAKE],
    application = HiltTestApplication::class,
    qualifiers = "w360dp-h640dp-mdpi",
)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@OptIn(ExperimentalRoborazziApi::class)
class AiStoryTests {
    @get:Rule
    val testRule = ComprehensibleInputTestRule(this)

    @get:Rule
    val roborazziRule = RoborazziRule(
        options = RoborazziRule.Options(
            roborazziOptions = RoborazziOptions(
                compareOptions = RoborazziOptions.CompareOptions(
                    changeThreshold = 0.01f,
                ),
            ),
        ),
    )

    @Test
    fun `AI-generated stories can be read`() = testRule.runTest {
        // WHEN the user chooses to read an AI-Generated story
        goToStoryList()
        onStoryList().selectAiStory()
        // THEN a story generated by an AI is shown
        onStoryReader().assertStoryTextIsVisible(
            SampleStoriesData.aiGeneratedStory.paragraphs.first().germanSentences
        )
    }

    @Test
    fun `AI-generated story title can be read`() = testRule.runTest {
        // WHEN the user chooses to read an AI-Generated story
        goToStoryList()
        onStoryList().selectAiStory()
        // THEN the title of an a story generated by an AI is shown
        onStoryReader().assertStoryTitleIsShown(SampleStoriesData.aiGeneratedStory.germanTitle)
    }

    @Test
    fun `AI-generated stories can be translated`() = testRule.runTest {
        // GIVEN the user chooses to read an AI-Generated story
        goToStoryList()
        onStoryList().selectAiStory()

        onStoryReader {
            val paragraph = SampleStoriesData.aiGeneratedStory.paragraphs.first()

            // WHEN the user taps on a sentence
            tapOnSentence(paragraph.germanSentences.first())
            awaitIdle()

            // THEN the sentence is translated
            assertStoryTextIsVisible(paragraph.englishSentences)
        }
    }

    @Test
    fun `AI-generated story title can be translated`() = testRule.runTest {
        // WHEN the user chooses to read an AI-Generated story
        goToStoryList()
        onStoryList().selectAiStory()

        onStoryReader {
            // WHEN the user taps on the title
            tapOnSentence(SampleStoriesData.aiGeneratedStory.germanTitle)
            awaitIdle()

            // THEN the title is translated
            assertStoryTitleIsShown(SampleStoriesData.aiGeneratedStory.englishTitle)
        }
    }
}